### PR TITLE
adds m-a and m-c win64 builders for opt, debug, and l10n

### PR DESCRIPTION
**Pull request by lundjordan**
this is for: Bug 1139763 - daily backlog of win64 builds

I think this may just work. iiuc - I should be giving all these builders 0 and letting the Allocator work its magic.

### CODE REVIEW

**Comment by Callek** [comment]
L10n is a special beast, and needs manual intervention as far as I can tell. @rail ?

c.f.
https://github.com/mozilla/build-jacuzzi-allocator/blob/79a4e82ec8b569ce33ea76f4e335bc85c5bd267c/allocate.py#L189

**Comment by rail** [comment]
Yeah, this change is not enough.

**Comment by lundjordan** [comment]
okay, I give up. I see we just do a blanket 'if l10n: pass' but I'm not sure why.

I also see that we have l10n builders in config.json: https://github.com/mozilla/releng-jacuzzis/blob/master/config.json#L54

I found https://bugzil.la/982634 but it looks like that was before config.json so I'm not sure if I should be copying https://github.com/mozilla/releng-jacuzzis/commit/afa658ba799697278309fb6a3e0edadadc6fac4a#diff-7b7472194bde10e44f91cb690be1b01fR64

by copying I mean adding l10n builders manually to v1/builders/ and v1/machines/. I guess the idea here is to add l10n slaves that also do non l10n so we don't lock up jacuzzis while we aren't doing a set of l10n builds?

do I add more to v1/allocated ?

**Comment by Callek** [comment]
@lundjordan so, basically why we do the "pass" is so that we don't auto-expand the whole pool for l10n, we manually select them.

Which means of course that we need to manually create the machines/ and builders/ json files for the l10n ones you specify. And include them in this patch. (you could also, I suspect, manually run the allocation code with the pass for l10n commented out, to have it generate those files based on its own algo for you I suspect)

**Comment by lundjordan** [comment]
my last patch removes l10n from config.json and manually adds it to 3 slaves. I copied a similar behaviour I saw in the linux l10n ones.

after reading callek's feedback above, it sounds like that was the right thing to do. The question is now, do I add more windows builder slaves to jacuzzis or will that happen automatically?

either way, I think this is on a better track

**Comment by catlee** [comment]
So to get l10n working with jacuzzis, you need to add entries for the builders in config.json with more than zero allocated machines. The allocator will take care of picking machines and maintaining the v1/{builders,machines} files. The only thing that won't happen with l10n is automatically picking the "correct" number of machines for the jacuzzi, so you need to choose that.

**Comment by lundjordan** [comment]
squashed commits into single commit. r+ from rail

**Pull request merged**
